# Generated by Django 5.1 on 2024-09-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=30)),
                ("pw", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name="basket",
            fields=[
                ("seq", models.AutoField(primary_key=True, serialize=False)),
                ("user_seq", models.IntegerField()),
                ("product_seq", models.IntegerField()),
                ("cnt", models.IntegerField()),
                ("order", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="category",
            fields=[
                ("seq", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="cs",
            fields=[
                ("seq", models.AutoField(primary_key=True, serialize=False)),
                ("user_seq", models.IntegerField()),
                ("product_seq", models.IntegerField()),
                ("cs_no", models.IntegerField()),
                ("pw", models.IntegerField()),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("file", models.ImageField(blank=True, null=True, upload_to="")),
                ("reg_dt", models.DateTimeField(auto_now=True)),
                ("secret", models.IntegerField(default=0)),
                ("view_cnt", models.IntegerField()),
                ("reply", models.TextField()),
                ("reply_dt", models.DateTimeField(auto_now=True)),
                ("reply_check", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="like",
            fields=[
                ("seq", models.AutoField(primary_key=True, serialize=False)),
                ("user_seq", models.IntegerField()),
                ("product_seq", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                ("seq", models.AutoField(primary_key=True, serialize=False)),
                ("user_seq", models.IntegerField()),
                ("product_seq", models.IntegerField()),
                ("cnt", models.IntegerField()),
                ("payment", models.IntegerField()),
                ("invoice", models.CharField(max_length=255)),
                ("order_dt", models.DateTimeField(auto_now=True)),
                ("order_price", models.IntegerField()),
                ("delivery", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                ("seq", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("cnt", models.IntegerField()),
                ("price", models.IntegerField()),
                ("category", models.IntegerField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("detail", models.TextField()),
                ("reg_dt", models.DateTimeField(auto_now=True)),
                ("view_cnt", models.IntegerField()),
                ("sell_cnt", models.IntegerField()),
                ("like_cnt", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                ("seq", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=30)),
                ("pw", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=13)),
                ("point", models.IntegerField()),
                ("reg_dt", models.DateTimeField(auto_now=True)),
                ("del_user", models.IntegerField(default=0)),
                ("purchase", models.IntegerField()),
                ("birth", models.CharField(max_length=8)),
                ("agree", models.IntegerField(default=0)),
            ],
        ),
    ]
