# Generated by Django 5.1 on 2024-09-26 10:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("user_name", models.CharField(max_length=50)),
                ("user_phone", models.CharField(max_length=13)),
                ("user_point", models.IntegerField(default=0)),
                ("user_sign", models.DateTimeField(default=django.utils.timezone.now)),
                ("user_del", models.BooleanField(default=0)),
                ("user_pet", models.IntegerField(default=0)),
                ("user_acc_point", models.IntegerField(default=0)),
                ("user_grade", models.IntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_address", models.CharField(max_length=255)),
                ("machine_latitude", models.CharField(max_length=255)),
                ("machine_longitude", models.CharField(max_length=255)),
                ("machine_capacity", models.IntegerField()),
                ("machine_pet", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("product_point", models.IntegerField()),
                ("product_pet", models.IntegerField()),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("product_change", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="MachineUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_us_pet", models.IntegerField()),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skky.machine"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_cnt", models.IntegerField()),
                ("change_way", models.IntegerField(default=0)),
                (
                    "change_app_dt",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("change_dt", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skky.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("del_address", models.CharField(max_length=255)),
                ("del_status", models.IntegerField(default=0)),
                ("del_num", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skky.product"
                    ),
                ),
            ],
        ),
    ]
